# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a80a73ab2c90195184219278a8f2fd9242ff220794800c5fc505392f7358d5d2c9e3ca7a51275c9f8d0d1d9bb79bfc032494336de94cfa87b139e03542bec52

test:
  secret_key_base: eed28cb81bcd3b7ff1caa5c3098e23eaac36b56065688d9474bbfac5fca8d1addc6176f5478f2065b31c8b55ceddf6e8691243cb120630a6ae58f0f84daaea95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
